FROM golang:1.16 as builder

WORKDIR /app

COPY . ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /go-app

FROM alpine:3.14
RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /go-app .

EXPOSE 8080

CMD ["./go-app"]
